title: 'yzhao325.github.io'
description: "yifan zhao"
baseurl: "yzhao325.github.io"
url: "https://yzhao325.github.io"

header_pages:
  - index.md
  - research.md
  - outreach.md
  - contact.md

style: dark

footer: ''

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
