title: 'yzhao325.github.io'
description: "yifan zhao"
baseurl: "yzhao325.github.io"
url: "https://yzhao325.github.io"

header_pages:
  - index.md
  - research.md

style: dark

footer: 'contact me at amyzhao[at]asu.edu'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
